### ISSUE TITLE
Remove Openshift specific functionality from Kubernetes Maven Plugin (KMP)

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#101]
## Description
As of now, both Maven plugins (Openshift + Kubernetes) are just ports of Fabric8 Maven Plugin (FMP) with different names.
FMP provides functionality for both cluster brands. AS KMP is just a port of FMP, we can still see traces of OpenShift specifics in the codebase (e.g.  [s2i](https://github.com/eclipse/jkube/blob/374816b2fd3001065a3cbc94b261eb34974834b5/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java#L316), [openshiftPullSecret](https://github.com/eclipse/jkube/blob/374816b2fd3001065a3cbc94b261eb34974834b5/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java#L295), [openshiftDeployTimeoutSeconds](https://github.com/eclipse/jkube/blob/374816b2fd3001065a3cbc94b261eb34974834b5/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java#L231)...)

All of these properties and configurations should be moved to the appropriate plugin.

## Tasks:
- [x] Modify affected Mojos
- [x] Update plugin documentation to reflect new state + flags
- [x] Change [jkube-website](https://github.com/jkubeio/jkube-website) to generate documentation for both plugins using the configurable `kubernetes-maven-plugin-doc`

## Relates to:
- #53
