### ISSUE TITLE
KubernetesBuildTask: k8sBuild Generator - WebApp

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1207]
## Description

Child of #31 

k8sBuild Gradle task works with WebApp Generator.

- Any configuration setting should be part of the KubernetesExtension class (Tasks should have no Inputs)
- Any logic present in the current Mojos should be moved to JKube-kit

## AC
- [x] Tomcat (default) handler works #1231
- [x] Jetty handler works #1231
- [x] WildFly (app server) handler works #1276 
- [x] Custom handler works #1288
- [x] Generator configuration options can be overridden via DSL #1313
- [x] Documentation related to the generator in Gradle docs #1307

**Comment by sunix** [comment]
for `Custom handler works`
- quickstart: https://github.com/eclipse/jkube/pull/1288
- bug: https://github.com/eclipse/jkube/issues/1284

**Comment by sunix** [comment]
for `Documentation related to the generator in Gradle docs`
https://github.com/eclipse/jkube/pull/1307#event-6123065510

**Comment by sunix** [comment]
for `Generator configuration options can be overridden via DSL`
- quickstart: https://github.com/eclipse/jkube/pull/1313
