### ISSUE TITLE
Gradle-Enricher: ProjectLabelEnricher

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1262]
### Description

Child of #31

ProjectLabelEnricher works with Gradle

### AC
- [x] Enricher documentation is ported to Gradle #1331
- [x] Create IT to verify that `jkube.enricher.jkube-project-label.app` flag works as expected #1386
- [x] kubernetes.yml is generated as expected #1331
- [x] openshift.yml is generated as expected #1331

**Comment by Hrushi20** [comment]
Hey! What exactly is the use of IT module in the project. I am not understanding what exactly it is used for.
