### ISSUE TITLE
Gradle-Enricher: ReplicaCountEnricher

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1297]
### Description

Child of #31

Relates to #1240 #1060

ReplicaCountEnricher works with Gradle

### AC
- [x] Enricher documentation is ported to Gradle #1352
- [x] Create IT to verify that `jkube.replicas` flag works as expected #1060
- [x] kubernetes.yml is generated as expected #1060
- [x] openshift.yml is generated as expected #1060
