### ISSUE TITLE
Gradle-Enricher: ProjectEnricher

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1311]
### Description

Child of #31

ProjectEnricher works with Gradle

### AC
- [ ] Enricher documentation is ported to Gradle #1389
- [x] IT `openshift/project` is ported to Gradle (should already be covered by #1238)
- [x] openshift.yml is generated as expected (should already be covered by #1238)
