### ISSUE TITLE
Refactor Configuration Model

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#136]
## Description
All configuration model classes should be refactored to provide a consistent fluent DSL interface.
- All classes must have a builder (builder should be auto-generated [ide, lombok, etc.])
- All classes must include Javadoc documenting the usage and specifics of each configuration variable

## Tasks
- [x] Refactor `jkube-kit-common` model
- [x] Add Javadoc `jkube-kit-common` model
- [x] Remove Generic typed builders introduced in first step of Maven Decoupling (We now have a JKube, maven agnostic, specific model)
- [x] Refactor `jkube-kit-build-service-docker` configuration model
- [x] Refactor `jkube-kit-common` configuration model
- [x] Refactor `jkube-kit-config-image` configuration model
- [x] Refactor `jkube-kit-config-resource` configuration model
- [x] Refactor `jkube-kit-config-service` configuration model
- [x] Refactor `jkube-kit-maven-enricher-api` configuration model > rename artifact (jkube-kit)
- [x] Refactor `jkube-kit-maven-generator-api` configuration model > rename artifact (jkube-kit)
- [x] Refactor `jkube-kit-watcher-api` configuration model
- [x] Create Quickstart for JKube Kit
