### ISSUE TITLE
E2E: Create OpenLiberty tests

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#137]
## Description
Create E2E tests to verify OpenLiberty generator ~and enricher~ works as expected.

## Tasks
- [x] Create OpenLiberty project in https://github.com/jkubeio/jkube-integration-tests/tree/master/projects-to-be-tested (use Vert.x or Thorntail projects as reference)
- [x] Create new package openliberty in https://github.com/jkubeio/jkube-integration-tests/tree/master/it/src/test/java/org/eclipse/jkube/integrationtests
- [x] Create test for Kubernetes
- [x] Create test for OpenShift
- [x] Configure [pom.xml](https://github.com/jkubeio/jkube-integration-tests/blob/master/pom.xml) to run the tests in the [`other`](https://github.com/jkubeio/jkube-integration-tests/blob/c928689eca224ea47748e8cb8b609fa2bed9fbec/pom.xml#L342) profile

cc: @anandrkskd
