### ISSUE TITLE
E2E: Create Wildfly Swarm tests

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#156]
## Description
Create E2E tests to verify Wildfly Swarm generator works as expected.

Specific verifications:
 - Docker Image contains ENV variable AB_PROMETHEUS_OFF

## Tasks
- [x] Create new package wildflyswarm in https://github.com/jkubeio/jkube-integration-tests/tree/master/it/src/test/java/org/eclipse/jkube/integrationtests
- [x] Create test for Kubernetes
- [x] Create test for OpenShift
- [x] Create Wildfly Swarm project in https://github.com/jkubeio/jkube-integration-tests/tree/master/projects-to-be-tested (use Vert.x or Thorntail projects as reference)
- [x] Configure [pom.xml](https://github.com/jkubeio/jkube-integration-tests/blob/master/pom.xml) to run the tests in the [`other`](https://github.com/jkubeio/jkube-integration-tests/blob/c928689eca224ea47748e8cb8b609fa2bed9fbec/pom.xml#L342) profile

## References
- http://www.mastertheboss.com/jboss-server/wildfly-swarm/getting-started-with-wildfly-swarm
- https://www.phillip-kruger.com/post/hollowjars_deploymentscanner_and_why_wildflyswarm_is_cool/

cc: @anandrkskd
