### ISSUE TITLE
Remove @Deprecated fields from BuildConfiguration

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#189]
## Description

`BuildConfiguration` contains a deprecated field `dockerFileDir` that is used when building the image in Docker file mode.

Taking advantage we're moving away from FMP this field should be completely removed. This is a critical field.

## Tasks
- [x] Remove field from model class
- [x] Update plugin documentation
- [x] Check quick starts possibly using the field
- [x] Check e2e tests
