### ISSUE TITLE
Remove @Deprecated fields from AssemblyConfiguration

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#190]
## Description

`AssemblyConfiguration` contains several deprecated fields.

Taking advantage we're moving away from FMP these fields should be completely removed. 

## Tasks
- [x] Remove field from model class
- [x] Update plugin documentation
- [x] Check quick starts possibly using the fields
- [x] Check e2e tests
