### ISSUE TITLE
Remove @Deprecated fields from RunImageConfiguration

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#191]
## Description

`RunImageConfiguration` contains several deprecated fields, methods and enums.

Taking advantage we're moving away from FMP these fields should be completely removed. 

## Tasks
- [x] Remove field/method/enum from model class
- [x] Update plugin documentation
- [x] Check quick starts possibly using the field/method/enum
- [ ] Check e2e tests
