### ISSUE TITLE
Remove @Deprecated constructor from ClusterAccess

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#192]
## Description

`ClusterAccess` contains a deprecated constructor.

Taking advantage we're moving away from FMP this constructor should be completely removed. 

## Tasks
- [ ] Remove constructor from model class
- [ ] Update plugin documentation
- [ ] Check quick starts possibly using the constructor
- [ ] Check e2e tests
