### ISSUE TITLE
Spike remote dev: vscode-ext + config format

### ISSUE THREAD

**Issue by sunix** [eclipse/jkube#2074]
### Task description
Spike a vscode extension for remote dev. Part of https://github.com/eclipse/jkube/issues/1961

current work is in https://github.com/jkubeio/kport and https://github.com/jkubeio/vscode-kport
Proposal for next steps:
- [x]  https://github.com/jkubeio/kport/issues/1
- [x] [ALL] https://github.com/jkubeio/kport/issues/2
- [x] [ALL] Vidéo demo presentation of the project:
    - [x] part 1: Recap JKube remote-dev
    - [x] part 2: kubectl kport plugin
    - [x] part 3: VSCode kport extension and IDE server
- [x] **L**- [core] https://github.com/jkubeio/kport/issues/3
- [x] **S**- [kubectl] Packaging and downloadables -> automated, first release https://github.com/jkubeio/kport/releases/tag/1.0.0
- [x] **S**- [ide-server] Packaging and downloadables -> automated, first release https://github.com/jkubeio/kport/releases/tag/1.0.0

For later ?
- [ ] **M/L**- [vscode] Packaging and downloadables  https://github.com/jkubeio/kport/issues/5
- [ ] **S**- [vscode] init with command palette https://github.com/jkubeio/kport/issues/6
- [ ] **S**- [kubectl] Make sure it works on windows/macos https://github.com/jkubeio/kport/issues/7
- [ ] **M**- [ide-server] Communication with websocket/jsonrpc https://github.com/jkubeio/kport/issues/8
- [ ] **L**-[vscode] Communication with websocket/jsonrpc https://github.com/jkubeio/kport/issues/8
- [ ] **L**- Write integration tests for quarkus-sshd https://github.com/jkubeio/kport/issues/9

**Comment by sunix** [comment]
Proposal for next steps:
- [quarkus-kport] Clean up the native compilation mode and Quarkus ext
- [ALL] Refine the demo to make it shorter
- [ALL] Rename the project to kport and move it to jkube-io
- [kubectl] Packaging and downloads
- [ide-server] Packaging and downloads
- [vscode] Packaging and downloads
- [core] Move to fabric8 ?
- [core] Move to quarkus extensions to quarkiverse or quarkus
- [vscode] init with command palette
- [ide-server] Communication with websocket/jsonrpc
- [vscode] Communication with websocket/jsonrpc
- [kubectl] Test on windows

**Comment by manusa** [comment]
Closing as the relevant part is complete (as agreed in internal meeting)
