### ISSUE TITLE
[TBD] Add BuildPackConfiguration object to Image Configuration model

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2457]
### Component

JKube Kit

### Task description

Part of #439 

As a user, I want to be able to customize the behavior of Buildpacks CLI (pack) execution by providing its supported command-line flags, so that I can properly fine tune the generated container image.

We could introduce a configuration object related to buildpacks inside `<build>` configuration.

This could look something like this:

```xml
<plugin>
        <groupId>org.eclipse.jkube</groupId>
        <artifactId>kubernetes-maven-plugin</artifactId>
        <version>${jkube.version}</version>
        <configuration>
                 <images>
                        <image>
                                <name>foo/bar:latest</name>
                                <build>
                                  <buildpack>

                                    <!-- BuildPack configuration options -->

                                  </buildpack>
                                </build>
                          </image>
                    </images>
         </configuration>
 </plugin>
```

We can have the following fields in BuildPackConfiguration object:
- [ ] publish (boolean)
- [ ] clearCache (boolean)
- [ ] trustBuilder (boolean)
- [ ] dockerHost (String)
- [ ] cacheImage (String)
- [ ] cache (String)
- [ ] path (String)
- [ ] registry (String)
- [ ] network (String)
- [ ] pullPolicy (String)
- [ ] descriptor (String)
- [ ] defaultProcess (String)
- [ ] lifecycleImage (String)
- [ ] env (Map)
- [ ] envFiles (String list)
- [ ] buildpacks (String list)
- [ ] extensions (String list)
- [ ] volumes (String list)
- [ ] tags (String list)
- [ ] workspace (String)
- [ ] gid (int)
- [ ] previousImage (String)
- [ ] sbomOutputDir (String)
- [ ] reportOutputDir (String)
- [ ] creationTime (String)
- [ ] preBuildPacks (String list)
- [ ] postBuildPacks (String list)
- [ ] builderImage (String)
- [ ] runImage (String)

### Acceptance Criteria
- [ ] BuildPackConfiguration object added as a field in BuildConfiguration

**Comment by manusa** [comment]
We need to discuss the list of supported options, see if they are overlapping with the ones we might already have.

I'm not sure it's a good idea to completely expose every option.

**Comment by rohanKanojia** [comment]
As discussed we're not going to expose all the options for BuildPackConfiguration in initial phase.

Closing this issue
