### ISSUE TITLE
Add Maven Enforcer Plugin

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#29]
## Description
Project contains convergence issues with dependencies referenced across different modules. [Maven Enforce Plugin](https://maven.apache.org/enforcer/maven-enforcer-plugin/) should be set up to prevent these convergence issues.

## Tasks
- [x] Add maven convergence plugin to pom
- [x] Fix reported convergence issues
- [x] Use dependency management and Maven properties to reference/manage dependencies from a single place

## Relates to:
- https://github.com/eclipse/jkube/pull/26
