### ISSUE TITLE
Decouple JKube-Kit from Maven

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#30]
## Description
In order to be able to use JKube as an external library, JKube kit should be completely decoupled from any Maven dependencies

## Tasks
- [x] Remove all non-needed dependencies from `jkube-kit-common` and replicate them in the projects where needed -> #44
- [x] Move maven specific utils from `jkube-kit-common` to a separate "Maven only" project -> #44 
- [x] Remove maven dependencies from jkube-kit-config-image -> #45 
- [x] Move resource service implementation out of config model-> #46
  - Create module `resource/service` "Jkube Kit :: Resource :: Service"
  - Move package `org.eclipse.jkube.kit.config.service` in `config/resource` to the new module
- [x] Remove maven dependencies from jkube-kit-config-resource -> #46 
- [x] Remove maven dependencies from jkube-kit-build-api and jkube-kit-build-service-docker -> #48 
- [x] Remove maven dependencies from jkube-kit-build-maven -> #49
- ...

## Blocked by
- #29 #39

**Comment by rohanKanojia** [comment]
@manusa : oh, Did we miss something?
