### ISSUE TITLE
Rename Plugins' artifactIds to kubernetes-maven-plugins and openshift-maven-plugins

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#53]
Right now we have plugin `artifactIds` set to `k8s-maven-plugin` and `oc-maven-plugin`. We should rename it to `kubernetes-maven-plugin` since it would make it easier to get searched on maven central. But we should also preserve current plugin prefixes (`k8s` and `oc`). It's possible to do it as mentioned on this StackOverflow [post](https://stackoverflow.com/questions/2736373/how-to-rename-goals-in-maven).

**Comment by manusa** [comment]
## Tasks
- [ ] Rename current `kubernetes-maven-plugin` to `kubernetes-maven-plugin-parent`
- [ ] Rename current `openshift-maven-plugin` to `openshift-maven-plugin-parent`
- [ ] Rename current `k8s-maven-plugin` to `kubernetes-maven-plugin`
- [ ] Rename current `oc-maven-plugin` to `openshift-maven-plugin`
- [ ] Configure `kubernetes-maven-plugin` prefix to be `k8s`
- [ ] Configure `openshift-maven-plugin` prefix to be `oc`


## How to configure a Maven Plugin prefix
```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-plugin-plugin</artifactId>4
	<configuration>
		<goalPrefix>k8s</goalPrefix>
	</configuration>
        <!-- ..... -->
</plugin>
```
## See also
- https://maven.apache.org/guides/introduction/introduction-to-plugin-prefix-mapping.html

**Comment by manusa** [comment]
![image](https://user-images.githubusercontent.com/488391/76742043-ca860400-6770-11ea-8f26-1597d3ddddd9.png)
